severity: error

linters:

  BorderZero:
    enabled: true
    convention: zero

  ColorVariable:
    enabled: false

  BemDepth:
    enabled: true

  IdSelector:
    enabled: false

  DeclarationOrder:
    enabled: false

  ExtendDirective:
    enabled: false

  PlaceholderInExtend:
    enabled: false

  LeadingZero:
    enabled: false

  NameFormat:
    enabled: true

  PrivateNamingConvention:
    enabled: true
    prefix: _

  PropertySortOrder:
    enabled: false

  SpaceAfterVariableName:
    enabled: false

  QualifyingElement:
    enabled: false

  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM
    class_convention: ^(?!js-).*
    class_convention_explanation: should not be written in the form js-*
    ignored_names:
      - HW_badge
      - HW_badge_cont

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: false

  StringQuotes:
    enabled: true
    style: single_quotes
