language: node_js
node_js:
  - "6"
before_install:
  - rvm install 2.4.0
  - gem install scss_lint
env:
  global:
    - GIT_NAME: Travis CI
    - GIT_EMAIL: nobody@nobody.org
    - GITHUB_REPO: windtoday/windtoday.github.io
    - GIT_SOURCE: src/www
    - GIT_BRANCH: master

after_script:
  - |
      declare exitCode;
      # -- [1] -------------------------------------------------------
      $(npm bin)/travis-after-all
      exitCode=$?
      # -- [2] -------------------------------------------------------
      if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" -a $exitCode -eq 0 ]; then
        npm install git-update-ghpages
        npm run build && ./node_modules/.bin/git-update-ghpages -e
      fi
